# Generated by Django 3.2.9 on 2022-03-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ownerId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
