# Generated by Django 3.2.9 on 2022-03-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220320_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
