# Generated by Django 3.2.9 on 2022-03-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220321_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hints',
            field=models.CharField(default='', max_length=500),
        ),
    ]
