# Generated by Django 3.2.9 on 2022-03-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_hints'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='label',
            field=models.CharField(default='', max_length=10),
        ),
    ]
